# Stage 1: Build binary
FROM golang:1.16-alpine AS builder
WORKDIR /app

COPY . .
RUN go build -o myapp

# Stage 2: Create a minimal container
FROM alpine:latest
WORKDIR /root/

# Copy the binary from the builder stage
COPY --from=builder /app/myapp .

# Set the entry point of the container
CMD ["./myapp"]
